In [1]:
# Import dependencies
import pandas as pd

In [2]:
# read CSV file
df = pd.read_csv('/Users/meganconnelly/desktop/Project_3/Age-adjusted Opioid Mortality Rates† , Counts, and Percentages, by Race, Philadelphia, 2010-2020.csv')
df.head()

,"Age-adjusted Opioid Mortality Rates† , Counts, and Percentages, by Race, Philadelphia, 2010-2020",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,Non-Hispanic White,NaN,NaN,Non-Hispanic Black,NaN,NaN,Hispanic (any race),NaN,NaN,Other,NaN,NaN,NaN,NaN
1,Year,"Ageadjusted Rate per 100,000 residents",N,Percent,"Ageadjusted Rate per 100,000 residents",N,Percent,"Ageadjusted Rate per 100,000 residents",N,Percent,"Ageadjusted Rate per 100,000 residents",N,Percent,NaN,NaN
2,2010,30.2,198,66.70%,11.6,76,25.60%,13.6,23,7.70%,0,0,0,NaN,NaN
3,2011,36.1,246,63.20%,12.9,83,21.30%,29.4,56,14.40%,*,*,*,NaN,NaN
4,2012,41.4,280,66.20%,15.2,99,23.40%,21.8,41,9.70%,*,*,*,NaN,NaN

In [3]:
# rename columns
df = df.rename(columns={
    'Unnamed: 1': 'Non-Hispanic White : Age adjusted rate per 100,000 residents', 
    'Unnamed: 2': 'Number', 
    'Unnamed: 3': 'Percent',
    'Unnamed: 4': 'Non-Hispanic Black: Age adjusted rate per 100,000 residents ', 
    'Unnamed: 5': 'Number', 
    'Unnamed: 6': 'Percent',
    'Unnamed: 7': 'Hispanic (any race): Age adjusted rate per 100,000 residents',
    'Unnamed: 8': 'Number', 
    'Unnamed: 9': 'Percent',
    'Age-adjusted Opioid Mortality Rates† , Counts, and Percentages, by Race, Philadelphia, 2010-2020': 'Year'
})
# print the updated column names
print(df.columns)

Index(['Year', 'Non-Hispanic White : Age adjusted rate per 100,000 residents',
       'Number', 'Percent',
       'Non-Hispanic Black: Age adjusted rate per 100,000 residents ',
       'Number', 'Percent',
       'Hispanic (any race): Age adjusted rate per 100,000 residents',
       'Number', 'Percent', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14'],
      dtype='object')

In [4]:
# drop unwanted columns
df = df.drop(columns=['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14'])

In [5]:
# print the updated column names
print(df.columns)

Index(['Year', 'Non-Hispanic White : Age adjusted rate per 100,000 residents',
       'Number', 'Percent',
       'Non-Hispanic Black: Age adjusted rate per 100,000 residents ',
       'Number', 'Percent',
       'Hispanic (any race): Age adjusted rate per 100,000 residents',
       'Number', 'Percent'],
      dtype='object')

In [6]:
df.head()

,Year,"Non-Hispanic White : Age adjusted rate per 100,000 residents",Number,Percent,"Non-Hispanic Black: Age adjusted rate per 100,000 residents",Number,Percent,"Hispanic (any race): Age adjusted rate per 100,000 residents",Number,Percent
0,NaN,Non-Hispanic White,NaN,NaN,Non-Hispanic Black,NaN,NaN,Hispanic (any race),NaN,NaN
1,Year,"Ageadjusted Rate per 100,000 residents",N,Percent,"Ageadjusted Rate per 100,000 residents",N,Percent,"Ageadjusted Rate per 100,000 residents",N,Percent
2,2010,30.2,198,66.70%,11.6,76,25.60%,13.6,23,7.70%
3,2011,36.1,246,63.20%,12.9,83,21.30%,29.4,56,14.40%
4,2012,41.4,280,66.20%,15.2,99,23.40%,21.8,41,9.70%

In [7]:
# drop rows at index 0 and 1
df = df.drop(index=[0, 1])

In [14]:
df.head()

,Year,"Non-Hispanic White : Age adjusted rate per 100,000 residents",Number,Percent,"Non-Hispanic Black: Age adjusted rate per 100,000 residents",Number,Percent,"Hispanic (any race): Age adjusted rate per 100,000 residents",Number,Percent
0,2010,30.2,198,66.70%,11.6,76,25.60%,13.6,23,7.70%
1,2011,36.1,246,63.20%,12.9,83,21.30%,29.4,56,14.40%
2,2012,41.4,280,66.20%,15.2,99,23.40%,21.8,41,9.70%
3,2013,34.4,238,66.70%,10.7,68,19.00%,22.3,47,13.20%
4,2014,45.2,312,63.00%,16.6,112,22.60%,32.3,67,13.50%

In [12]:
# reset the index
df = df.reset_index(drop=True)
df

,Year,"Non-Hispanic White : Age adjusted rate per 100,000 residents",Number,Percent,"Non-Hispanic Black: Age adjusted rate per 100,000 residents",Number,Percent,"Hispanic (any race): Age adjusted rate per 100,000 residents",Number,Percent
0,2010,30.2,198,66.70%,11.6,76,25.60%,13.6,23,7.70%
1,2011,36.1,246,63.20%,12.9,83,21.30%,29.4,56,14.40%
2,2012,41.4,280,66.20%,15.2,99,23.40%,21.8,41,9.70%
3,2013,34.4,238,66.70%,10.7,68,19.00%,22.3,47,13.20%
4,2014,45.2,312,63.00%,16.6,112,22.60%,32.3,67,13.50%
5,2015,50.4,343,61.10%,22.1,145,25.80%,34.3,71,12.70%
6,2016,65,468,62.20%,25.2,169,22.50%,42.9,101,13.40%
7,2017,96.5,679,63.20%,34.5,228,21.20%,64.9,153,14.20%
8,2018,76.9,562,59.90%,33.8,239,25.50%,56.7,130,13.80%
9,2019,74.9,519,53.90%,40.4,267,27.70%,70.8,165,17.10%
10,2020,68.5,475,45.60%,57.2,378,36.30%,74.8,171,16.40%

In [13]:
# save the updated DataFrame as a new CSV file
df.to_csv('/Users/meganconnelly/desktop/opioid_mortality.csv', index=False)